// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/openshift/cert-manager-operator/pkg/operator/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// CertManagers returns a CertManagerInformer.
	CertManagers() CertManagerInformer
	// IstioCSRs returns a IstioCSRInformer.
	IstioCSRs() IstioCSRInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// CertManagers returns a CertManagerInformer.
func (v *version) CertManagers() CertManagerInformer {
	return &certManagerInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// IstioCSRs returns a IstioCSRInformer.
func (v *version) IstioCSRs() IstioCSRInformer {
	return &istioCSRInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
