apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trust-manager
  namespace: cert-manager
  labels:
    app: trust-manager
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/instance: trust-manager
    app.kubernetes.io/managed-by: cert-manager-operator
    app.kubernetes.io/part-of: cert-manager-operator
spec:
  commonName: "trust-manager.cert-manager.svc"
  dnsNames:
    - "trust-manager.cert-manager.svc"
  secretName: trust-manager-tls
  revisionHistoryLimit: 1
  issuerRef:
    name: cert-manager-operator-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
