apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/instance: trust-manager
    app.kubernetes.io/managed-by: cert-manager-operator
  name: trust-manager-metrics
  namespace: cert-manager
spec:
  type: ClusterIP
  ports:
    - name: https-metrics
      port: 9402
      protocol: TCP
      targetPort: 9402
  selector:
    app: trust-manager
