apiVersion: apps/v1
kind: Deployment
metadata:
  name: trust-manager
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/instance: trust-manager
    app.kubernetes.io/managed-by: cert-manager-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trust-manager
  template:
    metadata:
      labels:
        app: trust-manager
        app.kubernetes.io/name: trust-manager
        app.kubernetes.io/instance: trust-manager
    spec:
      serviceAccountName: trust-manager
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: trust-manager
          image: quay.io/jetstack/trust-manager:v0.16.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6443
              protocol: TCP
            - containerPort: 9402
              protocol: TCP
          readinessProbe:
            httpGet:
              port: 6060
              path: /readyz
            initialDelaySeconds: 3
            periodSeconds: 7
          args:
            - --log-level=1
            - --log-format=text
            - --metrics-port=9402
            - --readiness-probe-port=6060
            - --readiness-probe-path=/readyz
            - --trust-namespace=cert-manager
            - --webhook-host=0.0.0.0
            - --webhook-port=6443
            - --webhook-certificate-dir=/tls
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: trust-manager-tls
            defaultMode: 420
