apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/instance: trust-manager
    app.kubernetes.io/managed-by: cert-manager-operator
  name: trust-manager
  annotations:
    cert-manager.io/inject-ca-from: cert-manager/trust-manager
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: trust-manager
        namespace: cert-manager
        path: /validate-trust-cert-manager-io-v1alpha1-bundle
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: trust.cert-manager.io
    rules:
      - apiGroups:
          - trust.cert-manager.io
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
        resources:
          - bundles
    sideEffects: None
