apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trust-manager:leases
  namespace: cert-manager
  labels:
    app: trust-manager
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/instance: trust-manager
    app.kubernetes.io/managed-by: cert-manager-operator
    app.kubernetes.io/part-of: cert-manager-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trust-manager:leases
subjects:
  - kind: ServiceAccount
    name: trust-manager
    namespace: cert-manager
