version: "2"
run:
  concurrency: 4
  build-tags:
    - e2e
  modules-download-mode: vendor
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: false
output:
  path-prefix: ""
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
  disable:
    - gosec
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    errcheck:
      exclude-functions:
        - (k8s.io/client-go/tools/cache.SharedInformer).AddEventHandler
        - (github.com/cert-manager/cert-manager/pkg/client/clientset/versioned/typed/certmanager/v1.IssuerInterface).Delete
        - (github.com/cert-manager/cert-manager/pkg/client/clientset/versioned/typed/certmanager/v1.ClusterIssuerInterface).Delete
        - (k8s.io/client-go/kubernetes/typed/networking/v1.IngressInterface).Delete
        - (github.com/cert-manager/cert-manager/pkg/client/clientset/versioned/typed/certmanager/v1.CertificateInterface).Delete
        - (k8s.io/client-go/kubernetes/typed/core/v1.ConfigMapInterface).Delete
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
