apiVersion: operator.openshift.io/v1alpha1
kind: IstioCSR
metadata:
  name: default
  namespace: istio-csr          # ! Replace this with your preferred namespace name.
  annotations:
    "kubernetes.io/description": "Resource behavior is managed through IstioCSR featuregate, which is enabled by default. Please refer to the cert-manager documentation for more information on the istio-csr feature."
spec:
  istioCSRConfig:
    certManager:
      issuerRef:
        name: istio-csr-issuer  # ❗ Replace this with your own Issuer/ClusterIssuer name.
        kind: Issuer            # ❗ Replace this with the created kind, Issuer/ClusterIssuer.
        group: cert-manager.io
    istiodTLSConfig:
      trustDomain: cluster.local
    istio:
      namespace: istio-system   # ! Replace this with your own istio deployed namespace name.
