apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cert-manager-operator
    app.kubernetes.io/part-of: cert-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cert-manager-operator
    app.kubernetes.io/part-of: cert-manager-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      name: cert-manager-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: cert-manager-operator
      labels:
        name: cert-manager-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - arm64
                    - ppc64le
                    - s390x
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - command:
            - /usr/bin/cert-manager-operator
          args:
            - start
            - '--v=$(OPERATOR_LOG_LEVEL)'
            - '--trusted-ca-configmap=$(TRUSTED_CA_CONFIGMAP_NAME)'
            - '--cloud-credentials-secret=$(CLOUD_CREDENTIALS_SECRET_NAME)'
            - '--unsupported-addon-features=$(UNSUPPORTED_ADDON_FEATURES)'
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.targetNamespaces']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: cert-manager-operator
            - name: RELATED_IMAGE_CERT_MANAGER_WEBHOOK
              value: registry.stage.redhat.io/cert-manager/jetstack-cert-manager-rhel9:v1.18.6-1@sha256:fb60ba61ae7f629b3d37f50d0fa195ef5f6e890364f2e36591a418e439971097
            - name: RELATED_IMAGE_CERT_MANAGER_CA_INJECTOR
              value: registry.stage.redhat.io/cert-manager/jetstack-cert-manager-rhel9:v1.18.6-1@sha256:fb60ba61ae7f629b3d37f50d0fa195ef5f6e890364f2e36591a418e439971097
            - name: RELATED_IMAGE_CERT_MANAGER_CONTROLLER
              value: registry.stage.redhat.io/cert-manager/jetstack-cert-manager-rhel9:v1.18.6-1@sha256:fb60ba61ae7f629b3d37f50d0fa195ef5f6e890364f2e36591a418e439971097
            - name: RELATED_IMAGE_CERT_MANAGER_ACMESOLVER
              value: registry.stage.redhat.io/cert-manager/jetstack-cert-manager-acmesolver-rhel9:v1.18.6-1@sha256:5a71abcf3112fdfc4d7e72bbaef43bc339a49b815b01fab6345c94dc913b5f7f
            - name: RELATED_IMAGE_CERT_MANAGER_ISTIOCSR
              value: registry.stage.redhat.io/cert-manager/cert-manager-istio-csr-rhel9:v0.14.2-1@sha256:860a9e5c9ff99b72ce9c2b0bf872aa073449083d8a1272d4b6a701c77ad998ef
            - name: OPERAND_IMAGE_VERSION
              value: 1.18.6
            - name: ISTIOCSR_OPERAND_IMAGE_VERSION
              value: 0.14.2
            - name: OPERATOR_IMAGE_VERSION
              value: 1.18.2
            - name: OPERATOR_LOG_LEVEL
              value: '2'
            - name: TRUSTED_CA_CONFIGMAP_NAME
            - name: CLOUD_CREDENTIALS_SECRET_NAME
            - name: UNSUPPORTED_ADDON_FEATURES
          image: registry.stage.redhat.io/cert-manager/cert-manager-operator-rhel9:v1.18.2@sha256:2db68997b24097a63a4ec6bb044e4cc63314eac8dd8b3b49a56cc564d1694ddd
          imagePullPolicy: IfNotPresent
          name: cert-manager-operator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - 'ALL'
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            seccompProfile:
              type: 'RuntimeDefault'
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: tmp
          emptyDir: {}
