apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cert-manager-operator
    app.kubernetes.io/part-of: cert-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cert-manager-operator
    app.kubernetes.io/part-of: cert-manager-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      name: cert-manager-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: cert-manager-operator
      labels:
        name: cert-manager-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - arm64
                    - ppc64le
                    - s390x
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - command:
            - /usr/bin/cert-manager-operator
          args:
            - start
            - '--v=$(OPERATOR_LOG_LEVEL)'
            - '--trusted-ca-configmap=$(TRUSTED_CA_CONFIGMAP_NAME)'
            - '--cloud-credentials-secret=$(CLOUD_CREDENTIALS_SECRET_NAME)'
            - '--unsupported-addon-features=$(UNSUPPORTED_ADDON_FEATURES)'
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.targetNamespaces']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: cert-manager-operator
            - name: RELATED_IMAGE_CERT_MANAGER_WEBHOOK
              value: registry.stage.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:9144fd826b65687970a6a88a4e7e50cc9b4bf4b76d3c427f1de6899e6a79b7fa
            - name: RELATED_IMAGE_CERT_MANAGER_CA_INJECTOR
              value: registry.stage.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:9144fd826b65687970a6a88a4e7e50cc9b4bf4b76d3c427f1de6899e6a79b7fa
            - name: RELATED_IMAGE_CERT_MANAGER_CONTROLLER
              value: registry.stage.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:9144fd826b65687970a6a88a4e7e50cc9b4bf4b76d3c427f1de6899e6a79b7fa
            - name: RELATED_IMAGE_CERT_MANAGER_ACMESOLVER
              value: registry.stage.redhat.io/cert-manager/jetstack-cert-manager-acmesolver-rhel9@sha256:5e42c5983bf93e3d0f31de628dc7d96ceec6136cdcb5f9e22dd29cc5193951a0
            - name: RELATED_IMAGE_CERT_MANAGER_ISTIOCSR
              value: registry.stage.redhat.io/cert-manager/cert-manager-istio-csr-rhel9@sha256:ed4f77362a05546f5809ae3675f5c5e8093453e7785f580f93348419900c1f06
            - name: RELATED_IMAGE_CERT_MANAGER_TRUST_MANAGER
              value: registry.stage.redhat.io/cert-manager/cert-manager-trust-manager-rhel9@sha256:d0834b140e53cb2b96d30f227b0c7dcab3463eeab80049df608582c45c792a82
            - name: OPERAND_IMAGE_VERSION
              value: 1.19.6
            - name: ISTIOCSR_OPERAND_IMAGE_VERSION
              value: 0.16.0
            - name: TRUSTMANAGER_OPERAND_IMAGE_VERSION
              value: 0.20.3
            - name: OPERATOR_IMAGE_VERSION
              value: 1.19.2
            - name: OPERATOR_LOG_LEVEL
              value: '2'
            - name: TRUSTED_CA_CONFIGMAP_NAME
            - name: CLOUD_CREDENTIALS_SECRET_NAME
            - name: UNSUPPORTED_ADDON_FEATURES
          image: registry.stage.redhat.io/cert-manager/cert-manager-operator-rhel9@sha256:ebb988080e93a733111f641cda75c30fb773509e9e35d928fe41262871d0fa68
          imagePullPolicy: IfNotPresent
          name: cert-manager-operator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - 'ALL'
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            seccompProfile:
              type: 'RuntimeDefault'
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: tmp
          emptyDir: {}
