apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cert-manager-operator
    app.kubernetes.io/part-of: cert-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cert-manager-operator
    app.kubernetes.io/part-of: cert-manager-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      name: cert-manager-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: cert-manager-operator
      labels:
        name: cert-manager-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - arm64
                    - ppc64le
                    - s390x
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - command:
            - /usr/bin/cert-manager-operator
          args:
            - start
            - '--v=$(OPERATOR_LOG_LEVEL)'
            - '--trusted-ca-configmap=$(TRUSTED_CA_CONFIGMAP_NAME)'
            - '--cloud-credentials-secret=$(CLOUD_CREDENTIALS_SECRET_NAME)'
            - '--unsupported-addon-features=$(UNSUPPORTED_ADDON_FEATURES)'
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.targetNamespaces']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: cert-manager-operator
            - name: RELATED_IMAGE_CERT_MANAGER_WEBHOOK
              value: registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9:v1.20.4@sha256:b3305a06bff4a344ba1b19c8142d7e605fc723841981c97aab2310ff8a82c66d
            - name: RELATED_IMAGE_CERT_MANAGER_CA_INJECTOR
              value: registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9:v1.20.4@sha256:b3305a06bff4a344ba1b19c8142d7e605fc723841981c97aab2310ff8a82c66d
            - name: RELATED_IMAGE_CERT_MANAGER_CONTROLLER
              value: registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9:v1.20.4@sha256:b3305a06bff4a344ba1b19c8142d7e605fc723841981c97aab2310ff8a82c66d
            - name: RELATED_IMAGE_CERT_MANAGER_ACMESOLVER
              value: registry.redhat.io/cert-manager/jetstack-cert-manager-acmesolver-rhel9:v1.20.4@sha256:8ce8e3f21e49fda94f6c984e4777637e3773a099c6d74010a26e5e2743965739
            - name: RELATED_IMAGE_CERT_MANAGER_ISTIOCSR
              value: registry.redhat.io/cert-manager/cert-manager-istio-csr-rhel9:v0.16.0-3@sha256:f63c50a7465ce4222dc3bb9443056d5bfcb07ecba20fcd9dd6ee143bc591f446
            - name: RELATED_IMAGE_CERT_MANAGER_TRUST_MANAGER
              value: registry.redhat.io/cert-manager/cert-manager-trust-manager-rhel9:v0.20.3@sha256:1fef2bffce8c89631099fbf8cefaa031502d670817897660ccfa0a9aa8a9ebc7
            - name: OPERAND_IMAGE_VERSION
              value: 1.20.4
            - name: ISTIOCSR_OPERAND_IMAGE_VERSION
              value: 0.16.0
            - name: TRUSTMANAGER_OPERAND_IMAGE_VERSION
              value: 0.20.3
            - name: OPERATOR_IMAGE_VERSION
              value: 1.20.1
            - name: OPERATOR_LOG_LEVEL
              value: '2'
            - name: TRUSTED_CA_CONFIGMAP_NAME
            - name: CLOUD_CREDENTIALS_SECRET_NAME
            - name: UNSUPPORTED_ADDON_FEATURES
          image: registry.redhat.io/cert-manager/cert-manager-operator-rhel9:v1.20.1@sha256:207804f9237b0c2875f5252997312230c88726b5271c6419320958078dd7b7fd
          imagePullPolicy: IfNotPresent
          name: cert-manager-operator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - 'ALL'
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            seccompProfile:
              type: 'RuntimeDefault'
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: tmp
          emptyDir: {}
