apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cert-manager-operator
    app.kubernetes.io/part-of: cert-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cert-manager-operator
    app.kubernetes.io/part-of: cert-manager-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      name: cert-manager-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: cert-manager-operator
      labels:
        name: cert-manager-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - command:
            - /usr/bin/cert-manager-operator
          args:
            - start
            - '--v=$(OPERATOR_LOG_LEVEL)'
            - '--trusted-ca-configmap=$(TRUSTED_CA_CONFIGMAP_NAME)'
            - '--cloud-credentials-secret=$(CLOUD_CREDENTIALS_SECRET_NAME)'
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.targetNamespaces']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: cert-manager-operator
            - name: RELATED_IMAGE_CERT_MANAGER_WEBHOOK
              value: quay.io/jetstack/cert-manager-webhook:v1.12.3
            - name: RELATED_IMAGE_CERT_MANAGER_CA_INJECTOR
              value: quay.io/jetstack/cert-manager-cainjector:v1.12.3
            - name: RELATED_IMAGE_CERT_MANAGER_CONTROLLER
              value: quay.io/jetstack/cert-manager-controller:v1.12.3
            - name: RELATED_IMAGE_CERT_MANAGER_ACMESOLVER
              value: quay.io/jetstack/cert-manager-acmesolver:v1.12.3
            - name: OPERAND_IMAGE_VERSION
              value: 1.12.3
            - name: OPERATOR_IMAGE_VERSION
              value: 1.12.0
            - name: OPERATOR_LOG_LEVEL
              value: '2'
            - name: TRUSTED_CA_CONFIGMAP_NAME
            - name: CLOUD_CREDENTIALS_SECRET_NAME
          image: controller:latest
          imagePullPolicy: Always
          name: cert-manager-operator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - 'ALL'
            privileged: false
            runAsNonRoot: true
            seccompProfile:
              type: 'RuntimeDefault'
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
