// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// HTTP01ProxyLister helps list HTTP01Proxies.
// All objects returned here must be treated as read-only.
type HTTP01ProxyLister interface {
	// List lists all HTTP01Proxies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1alpha1.HTTP01Proxy, err error)
	// HTTP01Proxies returns an object that can list and get HTTP01Proxies.
	HTTP01Proxies(namespace string) HTTP01ProxyNamespaceLister
	HTTP01ProxyListerExpansion
}

// hTTP01ProxyLister implements the HTTP01ProxyLister interface.
type hTTP01ProxyLister struct {
	listers.ResourceIndexer[*operatorv1alpha1.HTTP01Proxy]
}

// NewHTTP01ProxyLister returns a new HTTP01ProxyLister.
func NewHTTP01ProxyLister(indexer cache.Indexer) HTTP01ProxyLister {
	return &hTTP01ProxyLister{listers.New[*operatorv1alpha1.HTTP01Proxy](indexer, operatorv1alpha1.Resource("http01proxy"))}
}

// HTTP01Proxies returns an object that can list and get HTTP01Proxies.
func (s *hTTP01ProxyLister) HTTP01Proxies(namespace string) HTTP01ProxyNamespaceLister {
	return hTTP01ProxyNamespaceLister{listers.NewNamespaced[*operatorv1alpha1.HTTP01Proxy](s.ResourceIndexer, namespace)}
}

// HTTP01ProxyNamespaceLister helps list and get HTTP01Proxies.
// All objects returned here must be treated as read-only.
type HTTP01ProxyNamespaceLister interface {
	// List lists all HTTP01Proxies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1alpha1.HTTP01Proxy, err error)
	// Get retrieves the HTTP01Proxy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*operatorv1alpha1.HTTP01Proxy, error)
	HTTP01ProxyNamespaceListerExpansion
}

// hTTP01ProxyNamespaceLister implements the HTTP01ProxyNamespaceLister
// interface.
type hTTP01ProxyNamespaceLister struct {
	listers.ResourceIndexer[*operatorv1alpha1.HTTP01Proxy]
}
