// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TrustManagerLister helps list TrustManagers.
// All objects returned here must be treated as read-only.
type TrustManagerLister interface {
	// List lists all TrustManagers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1alpha1.TrustManager, err error)
	// Get retrieves the TrustManager from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*operatorv1alpha1.TrustManager, error)
	TrustManagerListerExpansion
}

// trustManagerLister implements the TrustManagerLister interface.
type trustManagerLister struct {
	listers.ResourceIndexer[*operatorv1alpha1.TrustManager]
}

// NewTrustManagerLister returns a new TrustManagerLister.
func NewTrustManagerLister(indexer cache.Indexer) TrustManagerLister {
	return &trustManagerLister{listers.New[*operatorv1alpha1.TrustManager](indexer, operatorv1alpha1.Resource("trustmanager"))}
}
