// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
)

// ApproverPolicyConfigApplyConfiguration represents a declarative configuration of the ApproverPolicyConfig type for use
// with apply.
//
// ApproverPolicyConfig controls creation of a CertificateRequestPolicy for the
// trust-manager webhook certificate.
type ApproverPolicyConfigApplyConfiguration struct {
	// policy controls whether a CertificateRequestPolicy and the RBAC that
	// allows cert-manager to use it are created.
	// "Enabled" creates CertificateRequestPolicy trust-manager-policy.
	// "Disabled" does not create it (default).
	Policy *operatorv1alpha1.Mode `json:"policy,omitempty"`
}

// ApproverPolicyConfigApplyConfiguration constructs a declarative configuration of the ApproverPolicyConfig type for use with
// apply.
func ApproverPolicyConfig() *ApproverPolicyConfigApplyConfiguration {
	return &ApproverPolicyConfigApplyConfiguration{}
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *ApproverPolicyConfigApplyConfiguration) WithPolicy(value operatorv1alpha1.Mode) *ApproverPolicyConfigApplyConfiguration {
	b.Policy = &value
	return b
}
