// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
)

// ApproverPolicyConfigApplyConfiguration represents a declarative configuration of the ApproverPolicyConfig type for use
// with apply.
//
// ApproverPolicyConfig controls creation of a CertificateRequestPolicy for the
// trust-manager webhook certificate.
type ApproverPolicyConfigApplyConfiguration struct {
	// bootstrapResources controls whether the operator automatically provisions
	// supporting prerequisite resources, such as the CertificateRequestPolicy and
	// associated RBAC bindings, required for approver-policy to function.
	//
	// Setting this to "Enabled" requires cert-manager approver-policy to be installed.
	BootstrapResources *operatorv1alpha1.Mode `json:"bootstrapResources,omitempty"`
}

// ApproverPolicyConfigApplyConfiguration constructs a declarative configuration of the ApproverPolicyConfig type for use with
// apply.
func ApproverPolicyConfig() *ApproverPolicyConfigApplyConfiguration {
	return &ApproverPolicyConfigApplyConfiguration{}
}

// WithBootstrapResources sets the BootstrapResources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootstrapResources field is set to the value of the last call.
func (b *ApproverPolicyConfigApplyConfiguration) WithBootstrapResources(value operatorv1alpha1.Mode) *ApproverPolicyConfigApplyConfiguration {
	b.BootstrapResources = &value
	return b
}
