// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "github.com/cert-manager/cert-manager/pkg/apis/meta/v1"
)

// CertManagerConfigApplyConfiguration represents a declarative configuration of the CertManagerConfig type for use
// with apply.
//
// CertManagerConfig is for configuring cert-manager specifics.
type CertManagerConfigApplyConfiguration struct {
	// issuerRef contains details of the referenced object used for obtaining certificates.
	// When `issuerRef.Kind` is `Issuer`, it must exist in the `.spec.istioCSRConfig.istio.namespace`.
	// This field is immutable once set.
	IssuerRef *v1.IssuerReference `json:"issuerRef,omitempty"`
	// istioCACertificate when provided, the operator will use the CA certificate from the specified ConfigMap.
	// If empty, the operator will automatically extract the CA certificate from the Secret containing the istiod certificate obtained from cert-manager.
	IstioCACertificate *ConfigMapReferenceApplyConfiguration `json:"istioCACertificate,omitempty"`
}

// CertManagerConfigApplyConfiguration constructs a declarative configuration of the CertManagerConfig type for use with
// apply.
func CertManagerConfig() *CertManagerConfigApplyConfiguration {
	return &CertManagerConfigApplyConfiguration{}
}

// WithIssuerRef sets the IssuerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IssuerRef field is set to the value of the last call.
func (b *CertManagerConfigApplyConfiguration) WithIssuerRef(value v1.IssuerReference) *CertManagerConfigApplyConfiguration {
	b.IssuerRef = &value
	return b
}

// WithIstioCACertificate sets the IstioCACertificate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IstioCACertificate field is set to the value of the last call.
func (b *CertManagerConfigApplyConfiguration) WithIstioCACertificate(value *ConfigMapReferenceApplyConfiguration) *CertManagerConfigApplyConfiguration {
	b.IstioCACertificate = value
	return b
}
