// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// CertManagerSchedulingApplyConfiguration represents a declarative configuration of the CertManagerScheduling type for use
// with apply.
//
// CertManagerScheduling describes the scheduling configurations for the cert-manager operands,
// namely the controller, webhook and cainjector.
type CertManagerSchedulingApplyConfiguration struct {
	// NodeSelector is a selector which must be true for the pod to fit on a node.
	// Selector which must match a node's labels for the pod to be scheduled on that node.
	// More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
	// Tolerations are attached to the pod to tolerate any taint that matches the
	// taint's key, value and effect using the toleration's matching operator.
	// More info: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
	Tolerations []v1.Toleration `json:"tolerations,omitempty"`
}

// CertManagerSchedulingApplyConfiguration constructs a declarative configuration of the CertManagerScheduling type for use with
// apply.
func CertManagerScheduling() *CertManagerSchedulingApplyConfiguration {
	return &CertManagerSchedulingApplyConfiguration{}
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *CertManagerSchedulingApplyConfiguration) WithNodeSelector(entries map[string]string) *CertManagerSchedulingApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *CertManagerSchedulingApplyConfiguration) WithTolerations(values ...v1.Toleration) *CertManagerSchedulingApplyConfiguration {
	for i := range values {
		b.Tolerations = append(b.Tolerations, values[i])
	}
	return b
}
