// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// CertManagerResourceRequirementsApplyConfiguration represents a declarative configuration of the CertManagerResourceRequirements type for use
// with apply.
//
// CertManagerResourceRequirements describes the compute resource requirements for the cert-manager operands,
// namely the controller, webhook and cainjector.
type CertManagerResourceRequirementsApplyConfiguration struct {
	// Limits describes the maximum amount of compute resources allowed.
	// More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
	Limits *v1.ResourceList `json:"limits,omitempty"`
	// Requests describes the minimum amount of compute resources required.
	// If Requests is omitted for a container, it defaults to Limits if that is explicitly specified,
	// otherwise to an implementation-defined value.
	// More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
	Requests *v1.ResourceList `json:"requests,omitempty"`
}

// CertManagerResourceRequirementsApplyConfiguration constructs a declarative configuration of the CertManagerResourceRequirements type for use with
// apply.
func CertManagerResourceRequirements() *CertManagerResourceRequirementsApplyConfiguration {
	return &CertManagerResourceRequirementsApplyConfiguration{}
}

// WithLimits sets the Limits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Limits field is set to the value of the last call.
func (b *CertManagerResourceRequirementsApplyConfiguration) WithLimits(value v1.ResourceList) *CertManagerResourceRequirementsApplyConfiguration {
	b.Limits = &value
	return b
}

// WithRequests sets the Requests field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Requests field is set to the value of the last call.
func (b *CertManagerResourceRequirementsApplyConfiguration) WithRequests(value v1.ResourceList) *CertManagerResourceRequirementsApplyConfiguration {
	b.Requests = &value
	return b
}
