// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1 "github.com/openshift/api/operator/v1"
	v1 "github.com/openshift/client-go/operator/applyconfigurations/operator/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// CertManagerSpecApplyConfiguration represents a declarative configuration of the CertManagerSpec type for use
// with apply.
//
// CertManagerSpec defines the desired state of CertManager.
type CertManagerSpecApplyConfiguration struct {
	v1.OperatorSpecApplyConfiguration `json:",inline"`
	// ControllerConfig specifies further customization options for the controller's deployment spec.
	//
	// Possible customizations include the following,
	//
	// For OverrideArgs,
	// This field appends values to .spec.template.spec.containers[...].args. The container
	// that will be selected will be based on image present on the spec. Possible values are,
	// Eg:
	// - "--acme-http01-solver-nameservers="8.8.8.8:53,1.1.1.1:53"
	// - "--dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53"
	// - "--dns01-recursive-nameservers-only"
	//
	// For OverrideEnvs,
	// This field appends values to .spec.template.spec.containers[...].env. The container
	// that will be selected will be based on image present on the spec. Possible values are,
	// Eg:
	// - "HTTP_PROXY": "http://proxy:8080"
	ControllerConfig *DeploymentConfigApplyConfiguration `json:"controllerConfig,omitempty"`
	// WebhookConfig specifies further customization options for the webhook's deployment spec.
	//
	// Possible customizations include the following,
	//
	// For OverrideArgs,
	// --config string                                Path to a file containing a WebhookConfiguration object used to configure the webhook
	// --dynamic-serving-ca-secret-name string        name of the secret used to store the CA that signs serving certificates
	// --dynamic-serving-ca-secret-namespace string   namespace of the secret used to store the CA that signs serving certificates
	// --dynamic-serving-dns-names strings            DNS names that should be present on certificates generated by the dynamic serving CA
	// --v Level                                      number for the log level verbosity
	WebhookConfig *DeploymentConfigApplyConfiguration `json:"webhookConfig,omitempty"`
	// CAInjectorConfig specifies further customization options for the cainjector's deployment spec.
	//
	// Possible customizations include the following,
	//
	// For OverrideArgs,
	// --namespace string                          If set, this limits the scope of cainjector to a single namespace. If set, cainjector
	// will not update resources with certificates outside of the configured namespace.
	// --v Level                                   number for the log level verbosity
	CAInjectorConfig *DeploymentConfigApplyConfiguration `json:"cainjectorConfig,omitempty"`
	// DefaultNetworkPolicy enables the default network policy for cert-manager components.
	// When set to "true", the operator will create default network policies to secure
	// communication between cert-manager controller, webhook, and cainjector components.
	// When set to "false" or empty, no default network policies are created.
	// Valid values are: "true", "false", or empty (default: false).
	//
	// This field is immutable once set to "true" for security reasons. Network policies
	// cannot be disabled once enabled to prevent accidental security degradation.
	// Users should carefully plan their network policy requirements before enabling this field.
	DefaultNetworkPolicy *string `json:"defaultNetworkPolicy,omitempty"`
	// NetworkPolicies specifies the egress network policy configuration to be applied to cert-manager
	// pods/operands when DefaultNetworkPolicy is "true". By default, enabling network policies
	// creates a deny-all policy that blocks all outgoing traffic from cert-manager components.
	// Ingress rules are automatically handled by the operator based on the current running ports.
	// Use this field to provide the necessary egress policy rules that allow required outbound traffic
	// for cert-manager to function properly (e.g., API server communication, external issuer access, etc.).
	//
	// Each NetworkPolicy in this slice will be created as a separate Kubernetes NetworkPolicy
	// resource. Multiple policies can be defined to organize egress rules logically (e.g., separate
	// policies for different types of outbound traffic or different security zones).
	//
	// This field is only effective when DefaultNetworkPolicy is set to "true".
	// If DefaultNetworkPolicy is "true" but this field is not provided, cert-manager
	// components will be isolated with deny-all egress policies.
	//
	// This field is immutable once DefaultNetworkPolicy is set to "true" for security reasons.
	NetworkPolicies []NetworkPolicyApplyConfiguration `json:"networkPolicies,omitempty"`
}

// CertManagerSpecApplyConfiguration constructs a declarative configuration of the CertManagerSpec type for use with
// apply.
func CertManagerSpec() *CertManagerSpecApplyConfiguration {
	return &CertManagerSpecApplyConfiguration{}
}

// WithManagementState sets the ManagementState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementState field is set to the value of the last call.
func (b *CertManagerSpecApplyConfiguration) WithManagementState(value operatorv1.ManagementState) *CertManagerSpecApplyConfiguration {
	b.OperatorSpecApplyConfiguration.ManagementState = &value
	return b
}

// WithLogLevel sets the LogLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogLevel field is set to the value of the last call.
func (b *CertManagerSpecApplyConfiguration) WithLogLevel(value operatorv1.LogLevel) *CertManagerSpecApplyConfiguration {
	b.OperatorSpecApplyConfiguration.LogLevel = &value
	return b
}

// WithOperatorLogLevel sets the OperatorLogLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OperatorLogLevel field is set to the value of the last call.
func (b *CertManagerSpecApplyConfiguration) WithOperatorLogLevel(value operatorv1.LogLevel) *CertManagerSpecApplyConfiguration {
	b.OperatorSpecApplyConfiguration.OperatorLogLevel = &value
	return b
}

// WithUnsupportedConfigOverrides sets the UnsupportedConfigOverrides field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnsupportedConfigOverrides field is set to the value of the last call.
func (b *CertManagerSpecApplyConfiguration) WithUnsupportedConfigOverrides(value runtime.RawExtension) *CertManagerSpecApplyConfiguration {
	b.OperatorSpecApplyConfiguration.UnsupportedConfigOverrides = &value
	return b
}

// WithObservedConfig sets the ObservedConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedConfig field is set to the value of the last call.
func (b *CertManagerSpecApplyConfiguration) WithObservedConfig(value runtime.RawExtension) *CertManagerSpecApplyConfiguration {
	b.OperatorSpecApplyConfiguration.ObservedConfig = &value
	return b
}

// WithControllerConfig sets the ControllerConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControllerConfig field is set to the value of the last call.
func (b *CertManagerSpecApplyConfiguration) WithControllerConfig(value *DeploymentConfigApplyConfiguration) *CertManagerSpecApplyConfiguration {
	b.ControllerConfig = value
	return b
}

// WithWebhookConfig sets the WebhookConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WebhookConfig field is set to the value of the last call.
func (b *CertManagerSpecApplyConfiguration) WithWebhookConfig(value *DeploymentConfigApplyConfiguration) *CertManagerSpecApplyConfiguration {
	b.WebhookConfig = value
	return b
}

// WithCAInjectorConfig sets the CAInjectorConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CAInjectorConfig field is set to the value of the last call.
func (b *CertManagerSpecApplyConfiguration) WithCAInjectorConfig(value *DeploymentConfigApplyConfiguration) *CertManagerSpecApplyConfiguration {
	b.CAInjectorConfig = value
	return b
}

// WithDefaultNetworkPolicy sets the DefaultNetworkPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultNetworkPolicy field is set to the value of the last call.
func (b *CertManagerSpecApplyConfiguration) WithDefaultNetworkPolicy(value string) *CertManagerSpecApplyConfiguration {
	b.DefaultNetworkPolicy = &value
	return b
}

// WithNetworkPolicies adds the given value to the NetworkPolicies field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NetworkPolicies field.
func (b *CertManagerSpecApplyConfiguration) WithNetworkPolicies(values ...*NetworkPolicyApplyConfiguration) *CertManagerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNetworkPolicies")
		}
		b.NetworkPolicies = append(b.NetworkPolicies, *values[i])
	}
	return b
}
