// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ConfigMapReferenceApplyConfiguration represents a declarative configuration of the ConfigMapReference type for use
// with apply.
//
// ConfigMapReference holds the details of a configmap.
type ConfigMapReferenceApplyConfiguration struct {
	// name of the ConfigMap.
	Name *string `json:"name,omitempty"`
	// namespace in which the ConfigMap exists. If empty, ConfigMap will be looked up in IstioCSR created namespace.
	Namespace *string `json:"namespace,omitempty"`
	// key name holding the required data.
	Key *string `json:"key,omitempty"`
}

// ConfigMapReferenceApplyConfiguration constructs a declarative configuration of the ConfigMapReference type for use with
// apply.
func ConfigMapReference() *ConfigMapReferenceApplyConfiguration {
	return &ConfigMapReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ConfigMapReferenceApplyConfiguration) WithName(value string) *ConfigMapReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ConfigMapReferenceApplyConfiguration) WithNamespace(value string) *ConfigMapReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *ConfigMapReferenceApplyConfiguration) WithKey(value string) *ConfigMapReferenceApplyConfiguration {
	b.Key = &value
	return b
}
