// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ControllerConfigApplyConfiguration represents a declarative configuration of the ControllerConfig type for use
// with apply.
type ControllerConfigApplyConfiguration struct {
	Labels map[string]string `json:"labels,omitempty"`
}

// ControllerConfigApplyConfiguration constructs a declarative configuration of the ControllerConfig type for use with
// apply.
func ControllerConfig() *ControllerConfigApplyConfiguration {
	return &ControllerConfigApplyConfiguration{}
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ControllerConfigApplyConfiguration) WithLabels(entries map[string]string) *ControllerConfigApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}
