// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
)

// DefaultCAPackageConfigApplyConfiguration represents a declarative configuration of the DefaultCAPackageConfig type for use
// with apply.
//
// DefaultCAPackageConfig configures the default CA package feature for trust-manager.
type DefaultCAPackageConfigApplyConfiguration struct {
	// policy controls whether the default CA package feature is enabled.
	// When set to "Enabled", the operator will inject OpenShift's trusted CA bundle
	// into trust-manager, enabling the "useDefaultCAs: true" source in Bundle resources.
	// When set to "Disabled", no default CA package is configured and Bundles cannot use useDefaultCAs (default behavior).
	Policy *operatorv1alpha1.DefaultCAPackagePolicy `json:"policy,omitempty"`
}

// DefaultCAPackageConfigApplyConfiguration constructs a declarative configuration of the DefaultCAPackageConfig type for use with
// apply.
func DefaultCAPackageConfig() *DefaultCAPackageConfigApplyConfiguration {
	return &DefaultCAPackageConfigApplyConfiguration{}
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *DefaultCAPackageConfigApplyConfiguration) WithPolicy(value operatorv1alpha1.DefaultCAPackagePolicy) *DefaultCAPackageConfigApplyConfiguration {
	b.Policy = &value
	return b
}
