// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
)

// HTTP01ProxySpecApplyConfiguration represents a declarative configuration of the HTTP01ProxySpec type for use
// with apply.
//
// HTTP01ProxySpec is the specification of the desired behavior of the HTTP01Proxy.
type HTTP01ProxySpecApplyConfiguration struct {
	// mode controls whether the HTTP01 challenge proxy is active and how it should be deployed.
	// DefaultDeployment enables the proxy with default configuration.
	// CustomDeployment enables the proxy with user-specified configuration.
	Mode *operatorv1alpha1.HTTP01ProxyMode `json:"mode,omitempty"`
	// customDeployment contains configuration options when mode is CustomDeployment.
	// This field is only valid when mode is CustomDeployment.
	CustomDeployment *HTTP01ProxyCustomDeploymentSpecApplyConfiguration `json:"customDeployment,omitempty"`
}

// HTTP01ProxySpecApplyConfiguration constructs a declarative configuration of the HTTP01ProxySpec type for use with
// apply.
func HTTP01ProxySpec() *HTTP01ProxySpecApplyConfiguration {
	return &HTTP01ProxySpecApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *HTTP01ProxySpecApplyConfiguration) WithMode(value operatorv1alpha1.HTTP01ProxyMode) *HTTP01ProxySpecApplyConfiguration {
	b.Mode = &value
	return b
}

// WithCustomDeployment sets the CustomDeployment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomDeployment field is set to the value of the last call.
func (b *HTTP01ProxySpecApplyConfiguration) WithCustomDeployment(value *HTTP01ProxyCustomDeploymentSpecApplyConfiguration) *HTTP01ProxySpecApplyConfiguration {
	b.CustomDeployment = value
	return b
}
