// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HTTP01ProxyCustomDeploymentSpecApplyConfiguration represents a declarative configuration of the HTTP01ProxyCustomDeploymentSpec type for use
// with apply.
//
// HTTP01ProxyCustomDeploymentSpec contains configuration for custom proxy deployment.
type HTTP01ProxyCustomDeploymentSpecApplyConfiguration struct {
	// internalPort specifies the internal port used by the proxy service.
	// Valid values are 1024-65535.
	InternalPort *int32 `json:"internalPort,omitempty"`
}

// HTTP01ProxyCustomDeploymentSpecApplyConfiguration constructs a declarative configuration of the HTTP01ProxyCustomDeploymentSpec type for use with
// apply.
func HTTP01ProxyCustomDeploymentSpec() *HTTP01ProxyCustomDeploymentSpecApplyConfiguration {
	return &HTTP01ProxyCustomDeploymentSpecApplyConfiguration{}
}

// WithInternalPort sets the InternalPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InternalPort field is set to the value of the last call.
func (b *HTTP01ProxyCustomDeploymentSpecApplyConfiguration) WithInternalPort(value int32) *HTTP01ProxyCustomDeploymentSpecApplyConfiguration {
	b.InternalPort = &value
	return b
}
