// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// HTTP01ProxyStatusApplyConfiguration represents a declarative configuration of the HTTP01ProxyStatus type for use
// with apply.
//
// HTTP01ProxyStatus is the most recently observed status of the HTTP01Proxy.
type HTTP01ProxyStatusApplyConfiguration struct {
	// conditions holds information about the current state of the HTTP01 proxy deployment.
	ConditionalStatusApplyConfiguration `json:",omitempty,inline"`
	// proxyImage is the name of the image and the tag used for deploying the proxy.
	ProxyImage *string `json:"proxyImage,omitempty"`
}

// HTTP01ProxyStatusApplyConfiguration constructs a declarative configuration of the HTTP01ProxyStatus type for use with
// apply.
func HTTP01ProxyStatus() *HTTP01ProxyStatusApplyConfiguration {
	return &HTTP01ProxyStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *HTTP01ProxyStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *HTTP01ProxyStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.ConditionalStatusApplyConfiguration.Conditions = append(b.ConditionalStatusApplyConfiguration.Conditions, *values[i])
	}
	return b
}

// WithProxyImage sets the ProxyImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProxyImage field is set to the value of the last call.
func (b *HTTP01ProxyStatusApplyConfiguration) WithProxyImage(value string) *HTTP01ProxyStatusApplyConfiguration {
	b.ProxyImage = &value
	return b
}
