// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
	internal "github.com/openshift/cert-manager-operator/pkg/operator/applyconfigurations/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// IstioCSRApplyConfiguration represents a declarative configuration of the IstioCSR type for use
// with apply.
type IstioCSRApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                             *IstioCSRSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                           *IstioCSRStatusApplyConfiguration `json:"status,omitempty"`
}

// IstioCSR constructs a declarative configuration of the IstioCSR type for use with
// apply.
func IstioCSR(name, namespace string) *IstioCSRApplyConfiguration {
	b := &IstioCSRApplyConfiguration{}
	b.WithName(name)
	b.WithNamespace(namespace)
	b.WithKind("IstioCSR")
	b.WithAPIVersion("operator.openshift.io/v1alpha1")
	return b
}

// ExtractIstioCSR extracts the applied configuration owned by fieldManager from
// istioCSR. If no managedFields are found in istioCSR for fieldManager, a
// IstioCSRApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// istioCSR must be a unmodified IstioCSR API object that was retrieved from the Kubernetes API.
// ExtractIstioCSR provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
// Experimental!
func ExtractIstioCSR(istioCSR *operatorv1alpha1.IstioCSR, fieldManager string) (*IstioCSRApplyConfiguration, error) {
	return extractIstioCSR(istioCSR, fieldManager, "")
}

// ExtractIstioCSRStatus is the same as ExtractIstioCSR except
// that it extracts the status subresource applied configuration.
// Experimental!
func ExtractIstioCSRStatus(istioCSR *operatorv1alpha1.IstioCSR, fieldManager string) (*IstioCSRApplyConfiguration, error) {
	return extractIstioCSR(istioCSR, fieldManager, "status")
}

func extractIstioCSR(istioCSR *operatorv1alpha1.IstioCSR, fieldManager string, subresource string) (*IstioCSRApplyConfiguration, error) {
	b := &IstioCSRApplyConfiguration{}
	err := managedfields.ExtractInto(istioCSR, internal.Parser().Type("com.github.openshift.cert-manager-operator.api.operator.v1alpha1.IstioCSR"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(istioCSR.Name)
	b.WithNamespace(istioCSR.Namespace)

	b.WithKind("IstioCSR")
	b.WithAPIVersion("operator.openshift.io/v1alpha1")
	return b, nil
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *IstioCSRApplyConfiguration) WithKind(value string) *IstioCSRApplyConfiguration {
	b.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *IstioCSRApplyConfiguration) WithAPIVersion(value string) *IstioCSRApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *IstioCSRApplyConfiguration) WithName(value string) *IstioCSRApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *IstioCSRApplyConfiguration) WithGenerateName(value string) *IstioCSRApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *IstioCSRApplyConfiguration) WithNamespace(value string) *IstioCSRApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *IstioCSRApplyConfiguration) WithUID(value types.UID) *IstioCSRApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *IstioCSRApplyConfiguration) WithResourceVersion(value string) *IstioCSRApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *IstioCSRApplyConfiguration) WithGeneration(value int64) *IstioCSRApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *IstioCSRApplyConfiguration) WithCreationTimestamp(value metav1.Time) *IstioCSRApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *IstioCSRApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *IstioCSRApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *IstioCSRApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *IstioCSRApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *IstioCSRApplyConfiguration) WithLabels(entries map[string]string) *IstioCSRApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *IstioCSRApplyConfiguration) WithAnnotations(entries map[string]string) *IstioCSRApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *IstioCSRApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *IstioCSRApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.OwnerReferences = append(b.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *IstioCSRApplyConfiguration) WithFinalizers(values ...string) *IstioCSRApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.Finalizers = append(b.Finalizers, values[i])
	}
	return b
}

func (b *IstioCSRApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *IstioCSRApplyConfiguration) WithSpec(value *IstioCSRSpecApplyConfiguration) *IstioCSRApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *IstioCSRApplyConfiguration) WithStatus(value *IstioCSRStatusApplyConfiguration) *IstioCSRApplyConfiguration {
	b.Status = value
	return b
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *IstioCSRApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.Name
}
