// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// IstiodTLSConfigApplyConfiguration represents a declarative configuration of the IstiodTLSConfig type for use
// with apply.
//
// IstiodTLSConfig is for configuring istiod certificate specifics.
type IstiodTLSConfigApplyConfiguration struct {
	// commonName is the common name to be set in the cert-manager.io Certificate created for istiod.
	// The commonName will be of the form istiod.<istio_namespace>.svc when not set.
	// This field can have a maximum of 64 characters.
	CommonName *string `json:"commonName,omitempty"`
	// trustDomain is the Istio cluster's trust domain, which will also be used for deriving the SPIFFE URI.
	// This field can have a maximum of 63 characters.
	TrustDomain *string `json:"trustDomain,omitempty"`
	// certificateDNSNames contains the additional DNS names to be added to the istiod certificate SAN.
	// This field can have a maximum of 25 entries.
	CertificateDNSNames []string `json:"certificateDNSNames,omitempty"`
	// certificateDuration is the validity period for the istio-csr and istiod certificates.
	CertificateDuration *v1.Duration `json:"certificateDuration,omitempty"`
	// certificateRenewBefore is the time before expiry to renew the istio-csr and istiod certificates.
	CertificateRenewBefore *v1.Duration `json:"certificateRenewBefore,omitempty"`
	// privateKeySize is the key size for the istio-csr and istiod certificates. Allowed values when privateKeyAlgorithm is RSA are 2048, 4096, 8192; and for ECDSA, they are 256, 384.
	// This field is immutable once set.
	PrivateKeySize *int32 `json:"privateKeySize,omitempty"`
	// privateKeyAlgorithm is the algorithm to use when generating private keys. Allowed values are RSA, and ECDSA.
	// This field is immutable once set.
	PrivateKeyAlgorithm *string `json:"privateKeyAlgorithm,omitempty"`
	// MaxCertificateDuration is the maximum validity duration that can be requested for a certificate.
	MaxCertificateDuration *v1.Duration `json:"maxCertificateDuration,omitempty"`
}

// IstiodTLSConfigApplyConfiguration constructs a declarative configuration of the IstiodTLSConfig type for use with
// apply.
func IstiodTLSConfig() *IstiodTLSConfigApplyConfiguration {
	return &IstiodTLSConfigApplyConfiguration{}
}

// WithCommonName sets the CommonName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommonName field is set to the value of the last call.
func (b *IstiodTLSConfigApplyConfiguration) WithCommonName(value string) *IstiodTLSConfigApplyConfiguration {
	b.CommonName = &value
	return b
}

// WithTrustDomain sets the TrustDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrustDomain field is set to the value of the last call.
func (b *IstiodTLSConfigApplyConfiguration) WithTrustDomain(value string) *IstiodTLSConfigApplyConfiguration {
	b.TrustDomain = &value
	return b
}

// WithCertificateDNSNames adds the given value to the CertificateDNSNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CertificateDNSNames field.
func (b *IstiodTLSConfigApplyConfiguration) WithCertificateDNSNames(values ...string) *IstiodTLSConfigApplyConfiguration {
	for i := range values {
		b.CertificateDNSNames = append(b.CertificateDNSNames, values[i])
	}
	return b
}

// WithCertificateDuration sets the CertificateDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateDuration field is set to the value of the last call.
func (b *IstiodTLSConfigApplyConfiguration) WithCertificateDuration(value v1.Duration) *IstiodTLSConfigApplyConfiguration {
	b.CertificateDuration = &value
	return b
}

// WithCertificateRenewBefore sets the CertificateRenewBefore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateRenewBefore field is set to the value of the last call.
func (b *IstiodTLSConfigApplyConfiguration) WithCertificateRenewBefore(value v1.Duration) *IstiodTLSConfigApplyConfiguration {
	b.CertificateRenewBefore = &value
	return b
}

// WithPrivateKeySize sets the PrivateKeySize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateKeySize field is set to the value of the last call.
func (b *IstiodTLSConfigApplyConfiguration) WithPrivateKeySize(value int32) *IstiodTLSConfigApplyConfiguration {
	b.PrivateKeySize = &value
	return b
}

// WithPrivateKeyAlgorithm sets the PrivateKeyAlgorithm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateKeyAlgorithm field is set to the value of the last call.
func (b *IstiodTLSConfigApplyConfiguration) WithPrivateKeyAlgorithm(value string) *IstiodTLSConfigApplyConfiguration {
	b.PrivateKeyAlgorithm = &value
	return b
}

// WithMaxCertificateDuration sets the MaxCertificateDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxCertificateDuration field is set to the value of the last call.
func (b *IstiodTLSConfigApplyConfiguration) WithMaxCertificateDuration(value v1.Duration) *IstiodTLSConfigApplyConfiguration {
	b.MaxCertificateDuration = &value
	return b
}
