// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// IstioCSRSpecApplyConfiguration represents a declarative configuration of the IstioCSRSpec type for use
// with apply.
type IstioCSRSpecApplyConfiguration struct {
	IstioCSRConfig   *IstioCSRConfigApplyConfiguration   `json:"istioCSRConfig,omitempty"`
	ControllerConfig *ControllerConfigApplyConfiguration `json:"controllerConfig,omitempty"`
}

// IstioCSRSpecApplyConfiguration constructs a declarative configuration of the IstioCSRSpec type for use with
// apply.
func IstioCSRSpec() *IstioCSRSpecApplyConfiguration {
	return &IstioCSRSpecApplyConfiguration{}
}

// WithIstioCSRConfig sets the IstioCSRConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IstioCSRConfig field is set to the value of the last call.
func (b *IstioCSRSpecApplyConfiguration) WithIstioCSRConfig(value *IstioCSRConfigApplyConfiguration) *IstioCSRSpecApplyConfiguration {
	b.IstioCSRConfig = value
	return b
}

// WithControllerConfig sets the ControllerConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControllerConfig field is set to the value of the last call.
func (b *IstioCSRSpecApplyConfiguration) WithControllerConfig(value *ControllerConfigApplyConfiguration) *IstioCSRSpecApplyConfiguration {
	b.ControllerConfig = value
	return b
}
