// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
	v1 "k8s.io/api/networking/v1"
)

// NetworkPolicyApplyConfiguration represents a declarative configuration of the NetworkPolicy type for use
// with apply.
//
// NetworkPolicy represents a custom network policy configuration for operator-managed components.
// It includes a name for identification and the network policy rules to be enforced.
type NetworkPolicyApplyConfiguration struct {
	// Name is a unique identifier for this network policy configuration.
	// This name will be used as part of the generated NetworkPolicy resource name.
	Name *string `json:"name,omitempty"`
	// ComponentName represents the different cert-manager components that can have network policies applied.
	ComponentName *operatorv1alpha1.ComponentName `json:"componentName,omitempty"`
	// egress is a list of egress rules to be applied to the selected pods. Outgoing traffic
	// is allowed if there are no NetworkPolicies selecting the pod (and cluster policy
	// otherwise allows the traffic), OR if the traffic matches at least one egress rule
	// across all of the NetworkPolicy objects whose podSelector matches the pod. If
	// this field is empty then this NetworkPolicy limits all outgoing traffic (and serves
	// solely to ensure that the pods it selects are isolated by default).
	// The operator will automatically handle ingress rules based on the current running ports.
	Egress []v1.NetworkPolicyEgressRule `json:"egress,omitempty"`
}

// NetworkPolicyApplyConfiguration constructs a declarative configuration of the NetworkPolicy type for use with
// apply.
func NetworkPolicy() *NetworkPolicyApplyConfiguration {
	return &NetworkPolicyApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NetworkPolicyApplyConfiguration) WithName(value string) *NetworkPolicyApplyConfiguration {
	b.Name = &value
	return b
}

// WithComponentName sets the ComponentName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ComponentName field is set to the value of the last call.
func (b *NetworkPolicyApplyConfiguration) WithComponentName(value operatorv1alpha1.ComponentName) *NetworkPolicyApplyConfiguration {
	b.ComponentName = &value
	return b
}

// WithEgress adds the given value to the Egress field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Egress field.
func (b *NetworkPolicyApplyConfiguration) WithEgress(values ...v1.NetworkPolicyEgressRule) *NetworkPolicyApplyConfiguration {
	for i := range values {
		b.Egress = append(b.Egress, values[i])
	}
	return b
}
