// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
)

// SecretTargetsConfigApplyConfiguration represents a declarative configuration of the SecretTargetsConfig type for use
// with apply.
//
// SecretTargetsConfig configures whether and how trust-manager can write
// trust bundles to Secrets.
type SecretTargetsConfigApplyConfiguration struct {
	// policy controls whether and how trust-manager can write trust bundles to Secrets.
	// Allowed values are "Disabled" or "Custom".
	// "Disabled" means trust-manager cannot write trust bundles to Secrets (default behavior).
	// "Custom" grants trust-manager read access  to all secrets cluster-wide,
	// and write access only to the secrets listed in authorizedSecrets.
	Policy *operatorv1alpha1.SecretTargetsPolicy `json:"policy,omitempty"`
	// authorizedSecrets is a list of specific secret names that trust-manager
	// is authorized to create and update. This field is only valid when policy is "Custom".
	AuthorizedSecrets []string `json:"authorizedSecrets,omitempty"`
}

// SecretTargetsConfigApplyConfiguration constructs a declarative configuration of the SecretTargetsConfig type for use with
// apply.
func SecretTargetsConfig() *SecretTargetsConfigApplyConfiguration {
	return &SecretTargetsConfigApplyConfiguration{}
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *SecretTargetsConfigApplyConfiguration) WithPolicy(value operatorv1alpha1.SecretTargetsPolicy) *SecretTargetsConfigApplyConfiguration {
	b.Policy = &value
	return b
}

// WithAuthorizedSecrets adds the given value to the AuthorizedSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AuthorizedSecrets field.
func (b *SecretTargetsConfigApplyConfiguration) WithAuthorizedSecrets(values ...string) *SecretTargetsConfigApplyConfiguration {
	for i := range values {
		b.AuthorizedSecrets = append(b.AuthorizedSecrets, values[i])
	}
	return b
}
