// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// TrustManagerStatusApplyConfiguration represents a declarative configuration of the TrustManagerStatus type for use
// with apply.
//
// TrustManagerStatus defines the observed state of TrustManager.
type TrustManagerStatusApplyConfiguration struct {
	// conditions holds information about the current state of the trust-manager deployment.
	ConditionalStatusApplyConfiguration `json:",omitempty,inline"`
	// trustManagerImage is the container image (name:tag) used for trust-manager.
	TrustManagerImage *string `json:"trustManagerImage,omitempty"`
}

// TrustManagerStatusApplyConfiguration constructs a declarative configuration of the TrustManagerStatus type for use with
// apply.
func TrustManagerStatus() *TrustManagerStatusApplyConfiguration {
	return &TrustManagerStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *TrustManagerStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *TrustManagerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.ConditionalStatusApplyConfiguration.Conditions = append(b.ConditionalStatusApplyConfiguration.Conditions, *values[i])
	}
	return b
}

// WithTrustManagerImage sets the TrustManagerImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrustManagerImage field is set to the value of the last call.
func (b *TrustManagerStatusApplyConfiguration) WithTrustManagerImage(value string) *TrustManagerStatusApplyConfiguration {
	b.TrustManagerImage = &value
	return b
}
