// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "github.com/cert-manager/cert-manager/pkg/apis/meta/v1"
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TrustManagerCertConfigApplyConfiguration represents a declarative configuration of the TrustManagerCertConfig type for use
// with apply.
//
// TrustManagerCertConfig configures the cert-manager Certificate used for the
// trust-manager webhook serving certificate.
type TrustManagerCertConfigApplyConfiguration struct {
	// certificateDuration is the requested validity period of the webhook TLS certificate.
	// When unset, cert-manager's default certificate duration is used.
	// Example: "8760h" for one year.
	CertificateDuration *v1.Duration `json:"certificateDuration,omitempty"`
	// certificateRenewBefore is how long before expiry cert-manager renews the webhook certificate.
	// When unset, cert-manager renews at one third of the certificate lifetime.
	CertificateRenewBefore *v1.Duration `json:"certificateRenewBefore,omitempty"`
	// issuerRef overrides the Issuer used for the webhook certificate.
	// When unset, the operator uses the self-signed Issuer it creates.
	// kind must be Issuer or ClusterIssuer. group must be cert-manager.io.
	IssuerRef *metav1.IssuerReference `json:"issuerRef,omitempty"`
	// privateKeyAlgorithm is the private key algorithm for the webhook certificate.
	// Allowed values are RSA, ECDSA, and Ed25519.
	PrivateKeyAlgorithm *string `json:"privateKeyAlgorithm,omitempty"`
	// privateKeyRotationPolicy controls whether a new private key is generated on re-issuance.
	// Allowed values are Always and Never.
	PrivateKeyRotationPolicy *string `json:"privateKeyRotationPolicy,omitempty"`
	// privateKeySize is the private key size for the webhook certificate.
	// RSA allows 2048, 4096, and 8192. ECDSA allows 256, 384, and 521. Ed25519 ignores this field.
	PrivateKeySize *int32 `json:"privateKeySize,omitempty"`
	// certificateSignatureAlgorithm is the signature algorithm for the webhook certificate.
	CertificateSignatureAlgorithm *string `json:"certificateSignatureAlgorithm,omitempty"`
	// propagateMetadataToSecret copies the labels and annotations the operator
	// sets on the webhook Certificate onto that Certificate's Secret.
	// "Enabled" copies them. "Disabled" does not (default).
	PropagateMetadataToSecret *operatorv1alpha1.Mode `json:"propagateMetadataToSecret,omitempty"`
}

// TrustManagerCertConfigApplyConfiguration constructs a declarative configuration of the TrustManagerCertConfig type for use with
// apply.
func TrustManagerCertConfig() *TrustManagerCertConfigApplyConfiguration {
	return &TrustManagerCertConfigApplyConfiguration{}
}

// WithCertificateDuration sets the CertificateDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateDuration field is set to the value of the last call.
func (b *TrustManagerCertConfigApplyConfiguration) WithCertificateDuration(value v1.Duration) *TrustManagerCertConfigApplyConfiguration {
	b.CertificateDuration = &value
	return b
}

// WithCertificateRenewBefore sets the CertificateRenewBefore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateRenewBefore field is set to the value of the last call.
func (b *TrustManagerCertConfigApplyConfiguration) WithCertificateRenewBefore(value v1.Duration) *TrustManagerCertConfigApplyConfiguration {
	b.CertificateRenewBefore = &value
	return b
}

// WithIssuerRef sets the IssuerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IssuerRef field is set to the value of the last call.
func (b *TrustManagerCertConfigApplyConfiguration) WithIssuerRef(value metav1.IssuerReference) *TrustManagerCertConfigApplyConfiguration {
	b.IssuerRef = &value
	return b
}

// WithPrivateKeyAlgorithm sets the PrivateKeyAlgorithm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateKeyAlgorithm field is set to the value of the last call.
func (b *TrustManagerCertConfigApplyConfiguration) WithPrivateKeyAlgorithm(value string) *TrustManagerCertConfigApplyConfiguration {
	b.PrivateKeyAlgorithm = &value
	return b
}

// WithPrivateKeyRotationPolicy sets the PrivateKeyRotationPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateKeyRotationPolicy field is set to the value of the last call.
func (b *TrustManagerCertConfigApplyConfiguration) WithPrivateKeyRotationPolicy(value string) *TrustManagerCertConfigApplyConfiguration {
	b.PrivateKeyRotationPolicy = &value
	return b
}

// WithPrivateKeySize sets the PrivateKeySize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateKeySize field is set to the value of the last call.
func (b *TrustManagerCertConfigApplyConfiguration) WithPrivateKeySize(value int32) *TrustManagerCertConfigApplyConfiguration {
	b.PrivateKeySize = &value
	return b
}

// WithCertificateSignatureAlgorithm sets the CertificateSignatureAlgorithm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateSignatureAlgorithm field is set to the value of the last call.
func (b *TrustManagerCertConfigApplyConfiguration) WithCertificateSignatureAlgorithm(value string) *TrustManagerCertConfigApplyConfiguration {
	b.CertificateSignatureAlgorithm = &value
	return b
}

// WithPropagateMetadataToSecret sets the PropagateMetadataToSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PropagateMetadataToSecret field is set to the value of the last call.
func (b *TrustManagerCertConfigApplyConfiguration) WithPropagateMetadataToSecret(value operatorv1alpha1.Mode) *TrustManagerCertConfigApplyConfiguration {
	b.PropagateMetadataToSecret = &value
	return b
}
