// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// TrustManagerConfigApplyConfiguration represents a declarative configuration of the TrustManagerConfig type for use
// with apply.
//
// TrustManagerConfig configures the trust-manager operand's behavior.
type TrustManagerConfigApplyConfiguration struct {
	// logLevel configures the verbosity of trust-manager logging.
	// Follows [Kubernetes logging guidelines](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md#what-method-to-use).
	LogLevel *int32 `json:"logLevel,omitempty"`
	// logFormat specifies the output format for trust-manager logging.
	// Supported formats are "text" and "json".
	LogFormat *string `json:"logFormat,omitempty"`
	// trustNamespace is the namespace where trust-manager looks for trust sources
	// (ConfigMaps and Secrets containing CA certificates).
	// Defaults to "cert-manager" if not specified.
	// This field is immutable once set.
	// This field can have a maximum of 63 characters.
	TrustNamespace *string `json:"trustNamespace,omitempty"`
	// secretTargets configures whether trust-manager can write trust bundles to Secrets.
	SecretTargets *SecretTargetsConfigApplyConfiguration `json:"secretTargets,omitempty"`
	// filterExpiredCertificates controls whether trust-manager filters out
	// expired certificates from trust bundles before distributing them.
	// When set to "Enabled", expired certificates are removed from bundles.
	// When set to "Disabled", expired certificates are included (default behavior).
	FilterExpiredCertificates *operatorv1alpha1.FilterExpiredCertificatesPolicy `json:"filterExpiredCertificates,omitempty"`
	// defaultCAPackage configures the default CA package for trust-manager.
	// When enabled, the operator will use OpenShift's trusted CA bundle injection mechanism.
	DefaultCAPackage *DefaultCAPackageConfigApplyConfiguration `json:"defaultCAPackage,omitempty"`
	// resources defines the compute resource requirements for the trust-manager pod.
	// ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
	Resources *v1.ResourceRequirements `json:"resources,omitempty"`
	// affinity defines scheduling constraints for the trust-manager pod.
	// ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
	Affinity *v1.Affinity `json:"affinity,omitempty"`
	// tolerations allows the trust-manager pod to be scheduled on tainted nodes.
	// ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
	Tolerations []v1.Toleration `json:"tolerations,omitempty"`
	// nodeSelector restricts which nodes the trust-manager pod can be scheduled on.
	// ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
}

// TrustManagerConfigApplyConfiguration constructs a declarative configuration of the TrustManagerConfig type for use with
// apply.
func TrustManagerConfig() *TrustManagerConfigApplyConfiguration {
	return &TrustManagerConfigApplyConfiguration{}
}

// WithLogLevel sets the LogLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogLevel field is set to the value of the last call.
func (b *TrustManagerConfigApplyConfiguration) WithLogLevel(value int32) *TrustManagerConfigApplyConfiguration {
	b.LogLevel = &value
	return b
}

// WithLogFormat sets the LogFormat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogFormat field is set to the value of the last call.
func (b *TrustManagerConfigApplyConfiguration) WithLogFormat(value string) *TrustManagerConfigApplyConfiguration {
	b.LogFormat = &value
	return b
}

// WithTrustNamespace sets the TrustNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrustNamespace field is set to the value of the last call.
func (b *TrustManagerConfigApplyConfiguration) WithTrustNamespace(value string) *TrustManagerConfigApplyConfiguration {
	b.TrustNamespace = &value
	return b
}

// WithSecretTargets sets the SecretTargets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretTargets field is set to the value of the last call.
func (b *TrustManagerConfigApplyConfiguration) WithSecretTargets(value *SecretTargetsConfigApplyConfiguration) *TrustManagerConfigApplyConfiguration {
	b.SecretTargets = value
	return b
}

// WithFilterExpiredCertificates sets the FilterExpiredCertificates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FilterExpiredCertificates field is set to the value of the last call.
func (b *TrustManagerConfigApplyConfiguration) WithFilterExpiredCertificates(value operatorv1alpha1.FilterExpiredCertificatesPolicy) *TrustManagerConfigApplyConfiguration {
	b.FilterExpiredCertificates = &value
	return b
}

// WithDefaultCAPackage sets the DefaultCAPackage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultCAPackage field is set to the value of the last call.
func (b *TrustManagerConfigApplyConfiguration) WithDefaultCAPackage(value *DefaultCAPackageConfigApplyConfiguration) *TrustManagerConfigApplyConfiguration {
	b.DefaultCAPackage = value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *TrustManagerConfigApplyConfiguration) WithResources(value v1.ResourceRequirements) *TrustManagerConfigApplyConfiguration {
	b.Resources = &value
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *TrustManagerConfigApplyConfiguration) WithAffinity(value v1.Affinity) *TrustManagerConfigApplyConfiguration {
	b.Affinity = &value
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *TrustManagerConfigApplyConfiguration) WithTolerations(values ...v1.Toleration) *TrustManagerConfigApplyConfiguration {
	for i := range values {
		b.Tolerations = append(b.Tolerations, values[i])
	}
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *TrustManagerConfigApplyConfiguration) WithNodeSelector(entries map[string]string) *TrustManagerConfigApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}
