// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// TrustManagerStatusApplyConfiguration represents a declarative configuration of the TrustManagerStatus type for use
// with apply.
type TrustManagerStatusApplyConfiguration struct {
	ConditionalStatusApplyConfiguration `json:",omitempty,inline"`
	TrustManagerImage                   *string                                           `json:"trustManagerImage,omitempty"`
	TrustNamespace                      *string                                           `json:"trustNamespace,omitempty"`
	SecretTargetsPolicy                 *operatorv1alpha1.SecretTargetsPolicy             `json:"secretTargetsPolicy,omitempty"`
	DefaultCAPackagePolicy              *operatorv1alpha1.DefaultCAPackagePolicy          `json:"defaultCAPackagePolicy,omitempty"`
	FilterExpiredCertificatesPolicy     *operatorv1alpha1.FilterExpiredCertificatesPolicy `json:"filterExpiredCertificatesPolicy,omitempty"`
}

// TrustManagerStatusApplyConfiguration constructs a declarative configuration of the TrustManagerStatus type for use with
// apply.
func TrustManagerStatus() *TrustManagerStatusApplyConfiguration {
	return &TrustManagerStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *TrustManagerStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *TrustManagerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.ConditionalStatusApplyConfiguration.Conditions = append(b.ConditionalStatusApplyConfiguration.Conditions, *values[i])
	}
	return b
}

// WithTrustManagerImage sets the TrustManagerImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrustManagerImage field is set to the value of the last call.
func (b *TrustManagerStatusApplyConfiguration) WithTrustManagerImage(value string) *TrustManagerStatusApplyConfiguration {
	b.TrustManagerImage = &value
	return b
}

// WithTrustNamespace sets the TrustNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrustNamespace field is set to the value of the last call.
func (b *TrustManagerStatusApplyConfiguration) WithTrustNamespace(value string) *TrustManagerStatusApplyConfiguration {
	b.TrustNamespace = &value
	return b
}

// WithSecretTargetsPolicy sets the SecretTargetsPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretTargetsPolicy field is set to the value of the last call.
func (b *TrustManagerStatusApplyConfiguration) WithSecretTargetsPolicy(value operatorv1alpha1.SecretTargetsPolicy) *TrustManagerStatusApplyConfiguration {
	b.SecretTargetsPolicy = &value
	return b
}

// WithDefaultCAPackagePolicy sets the DefaultCAPackagePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultCAPackagePolicy field is set to the value of the last call.
func (b *TrustManagerStatusApplyConfiguration) WithDefaultCAPackagePolicy(value operatorv1alpha1.DefaultCAPackagePolicy) *TrustManagerStatusApplyConfiguration {
	b.DefaultCAPackagePolicy = &value
	return b
}

// WithFilterExpiredCertificatesPolicy sets the FilterExpiredCertificatesPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FilterExpiredCertificatesPolicy field is set to the value of the last call.
func (b *TrustManagerStatusApplyConfiguration) WithFilterExpiredCertificatesPolicy(value operatorv1alpha1.FilterExpiredCertificatesPolicy) *TrustManagerStatusApplyConfiguration {
	b.FilterExpiredCertificatesPolicy = &value
	return b
}
