// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TrustManagerSpecApplyConfiguration represents a declarative configuration of the TrustManagerSpec type for use
// with apply.
//
// TrustManagerSpec defines the desired state of TrustManager.
// Note: trust-manager operand is always deployed in the cert-manager namespace.
type TrustManagerSpecApplyConfiguration struct {
	// trustManagerConfig configures the trust-manager operand's behavior.
	TrustManagerConfig *TrustManagerConfigApplyConfiguration `json:"trustManagerConfig,omitempty"`
	// controllerConfig configures the operator's behavior for resource creation.
	ControllerConfig *TrustManagerControllerConfigApplyConfiguration `json:"controllerConfig,omitempty"`
}

// TrustManagerSpecApplyConfiguration constructs a declarative configuration of the TrustManagerSpec type for use with
// apply.
func TrustManagerSpec() *TrustManagerSpecApplyConfiguration {
	return &TrustManagerSpecApplyConfiguration{}
}

// WithTrustManagerConfig sets the TrustManagerConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrustManagerConfig field is set to the value of the last call.
func (b *TrustManagerSpecApplyConfiguration) WithTrustManagerConfig(value *TrustManagerConfigApplyConfiguration) *TrustManagerSpecApplyConfiguration {
	b.TrustManagerConfig = value
	return b
}

// WithControllerConfig sets the ControllerConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControllerConfig field is set to the value of the last call.
func (b *TrustManagerSpecApplyConfiguration) WithControllerConfig(value *TrustManagerControllerConfigApplyConfiguration) *TrustManagerSpecApplyConfiguration {
	b.ControllerConfig = value
	return b
}
