// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// WebhookTLSConfigApplyConfiguration represents a declarative configuration of the WebhookTLSConfig type for use
// with apply.
//
// WebhookTLSConfig configures the trust-manager webhook TLS certificate.
type WebhookTLSConfigApplyConfiguration struct {
	// certificateDuration is the requested validity period of the webhook TLS certificate.
	// When unset, cert-manager's default certificate duration is used.
	// Example: "8760h" for one year.
	CertificateDuration *v1.Duration `json:"certificateDuration,omitempty"`
	// approverPolicy configures a CertificateRequestPolicy so that
	// cert-manager-approver-policy can auto-approve the webhook CertificateRequest.
	// Enable this when approver-policy is installed in the cluster.
	ApproverPolicy *ApproverPolicyConfigApplyConfiguration `json:"approverPolicy,omitempty"`
}

// WebhookTLSConfigApplyConfiguration constructs a declarative configuration of the WebhookTLSConfig type for use with
// apply.
func WebhookTLSConfig() *WebhookTLSConfigApplyConfiguration {
	return &WebhookTLSConfigApplyConfiguration{}
}

// WithCertificateDuration sets the CertificateDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateDuration field is set to the value of the last call.
func (b *WebhookTLSConfigApplyConfiguration) WithCertificateDuration(value v1.Duration) *WebhookTLSConfigApplyConfiguration {
	b.CertificateDuration = &value
	return b
}

// WithApproverPolicy sets the ApproverPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApproverPolicy field is set to the value of the last call.
func (b *WebhookTLSConfigApplyConfiguration) WithApproverPolicy(value *ApproverPolicyConfigApplyConfiguration) *WebhookTLSConfigApplyConfiguration {
	b.ApproverPolicy = value
	return b
}
