// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// WebhookTLSConfigApplyConfiguration represents a declarative configuration of the WebhookTLSConfig type for use
// with apply.
//
// WebhookTLSConfig configures the trust-manager webhook TLS certificate.
type WebhookTLSConfigApplyConfiguration struct {
	// certManager configures the cert-manager Certificate issued for the webhook.
	// When unset, the operator uses its self-signed Issuer and cert-manager defaults.
	CertManager *TrustManagerCertConfigApplyConfiguration `json:"certManager,omitempty"`
	// approverPolicy configures a CertificateRequestPolicy so that
	// cert-manager-approver-policy can auto-approve the webhook CertificateRequest.
	// Resources are created only when bootstrapResources is Enabled. If Enabled while the
	// CertificateRequestPolicy CRD is not installed, reconciliation fails until
	// approver-policy is installed or bootstrapResources is set to Disabled.
	ApproverPolicy *ApproverPolicyConfigApplyConfiguration `json:"approverPolicy,omitempty"`
}

// WebhookTLSConfigApplyConfiguration constructs a declarative configuration of the WebhookTLSConfig type for use with
// apply.
func WebhookTLSConfig() *WebhookTLSConfigApplyConfiguration {
	return &WebhookTLSConfigApplyConfiguration{}
}

// WithCertManager sets the CertManager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertManager field is set to the value of the last call.
func (b *WebhookTLSConfigApplyConfiguration) WithCertManager(value *TrustManagerCertConfigApplyConfiguration) *WebhookTLSConfigApplyConfiguration {
	b.CertManager = value
	return b
}

// WithApproverPolicy sets the ApproverPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApproverPolicy field is set to the value of the last call.
func (b *WebhookTLSConfigApplyConfiguration) WithApproverPolicy(value *ApproverPolicyConfigApplyConfiguration) *WebhookTLSConfigApplyConfiguration {
	b.ApproverPolicy = value
	return b
}
