//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManager) DeepCopyInto(out *CertManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManager.
func (in *CertManager) DeepCopy() *CertManager {
	if in == nil {
		return nil
	}
	out := new(CertManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerList) DeepCopyInto(out *CertManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerList.
func (in *CertManagerList) DeepCopy() *CertManagerList {
	if in == nil {
		return nil
	}
	out := new(CertManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerResourceRequirements) DeepCopyInto(out *CertManagerResourceRequirements) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerResourceRequirements.
func (in *CertManagerResourceRequirements) DeepCopy() *CertManagerResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(CertManagerResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpec) DeepCopyInto(out *CertManagerSpec) {
	*out = *in
	in.OperatorSpec.DeepCopyInto(&out.OperatorSpec)
	if in.ControllerConfig != nil {
		in, out := &in.ControllerConfig, &out.ControllerConfig
		*out = new(DeploymentConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.WebhookConfig != nil {
		in, out := &in.WebhookConfig, &out.WebhookConfig
		*out = new(DeploymentConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CAInjectorConfig != nil {
		in, out := &in.CAInjectorConfig, &out.CAInjectorConfig
		*out = new(DeploymentConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpec.
func (in *CertManagerSpec) DeepCopy() *CertManagerSpec {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerStatus) DeepCopyInto(out *CertManagerStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerStatus.
func (in *CertManagerStatus) DeepCopy() *CertManagerStatus {
	if in == nil {
		return nil
	}
	out := new(CertManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfig) DeepCopyInto(out *DeploymentConfig) {
	*out = *in
	if in.OverrideArgs != nil {
		in, out := &in.OverrideArgs, &out.OverrideArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OverrideEnv != nil {
		in, out := &in.OverrideEnv, &out.OverrideEnv
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OverrideLabels != nil {
		in, out := &in.OverrideLabels, &out.OverrideLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.OverrideResources.DeepCopyInto(&out.OverrideResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfig.
func (in *DeploymentConfig) DeepCopy() *DeploymentConfig {
	if in == nil {
		return nil
	}
	out := new(DeploymentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnsupportedConfigOverrides) DeepCopyInto(out *UnsupportedConfigOverrides) {
	*out = *in
	in.Controller.DeepCopyInto(&out.Controller)
	in.Webhook.DeepCopyInto(&out.Webhook)
	in.CAInjector.DeepCopyInto(&out.CAInjector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnsupportedConfigOverrides.
func (in *UnsupportedConfigOverrides) DeepCopy() *UnsupportedConfigOverrides {
	if in == nil {
		return nil
	}
	out := new(UnsupportedConfigOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnsupportedConfigOverridesForCertManagerCAInjector) DeepCopyInto(out *UnsupportedConfigOverridesForCertManagerCAInjector) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnsupportedConfigOverridesForCertManagerCAInjector.
func (in *UnsupportedConfigOverridesForCertManagerCAInjector) DeepCopy() *UnsupportedConfigOverridesForCertManagerCAInjector {
	if in == nil {
		return nil
	}
	out := new(UnsupportedConfigOverridesForCertManagerCAInjector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnsupportedConfigOverridesForCertManagerController) DeepCopyInto(out *UnsupportedConfigOverridesForCertManagerController) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnsupportedConfigOverridesForCertManagerController.
func (in *UnsupportedConfigOverridesForCertManagerController) DeepCopy() *UnsupportedConfigOverridesForCertManagerController {
	if in == nil {
		return nil
	}
	out := new(UnsupportedConfigOverridesForCertManagerController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnsupportedConfigOverridesForCertManagerWebhook) DeepCopyInto(out *UnsupportedConfigOverridesForCertManagerWebhook) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnsupportedConfigOverridesForCertManagerWebhook.
func (in *UnsupportedConfigOverridesForCertManagerWebhook) DeepCopy() *UnsupportedConfigOverridesForCertManagerWebhook {
	if in == nil {
		return nil
	}
	out := new(UnsupportedConfigOverridesForCertManagerWebhook)
	in.DeepCopyInto(out)
	return out
}
