// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/openshift/cert-manager-operator/apis/config/v1alpha1"
	scheme "github.com/openshift/cert-manager-operator/pkg/config/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CertmanagersGetter has a method to return a CertmanagerInterface.
// A group's client should implement this interface.
type CertmanagersGetter interface {
	Certmanagers() CertmanagerInterface
}

// CertmanagerInterface has methods to work with Certmanager resources.
type CertmanagerInterface interface {
	Create(ctx context.Context, certmanager *v1alpha1.Certmanager, opts v1.CreateOptions) (*v1alpha1.Certmanager, error)
	Update(ctx context.Context, certmanager *v1alpha1.Certmanager, opts v1.UpdateOptions) (*v1alpha1.Certmanager, error)
	UpdateStatus(ctx context.Context, certmanager *v1alpha1.Certmanager, opts v1.UpdateOptions) (*v1alpha1.Certmanager, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Certmanager, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CertmanagerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Certmanager, err error)
	CertmanagerExpansion
}

// certmanagers implements CertmanagerInterface
type certmanagers struct {
	client rest.Interface
}

// newCertmanagers returns a Certmanagers
func newCertmanagers(c *ConfigV1alpha1Client) *certmanagers {
	return &certmanagers{
		client: c.RESTClient(),
	}
}

// Get takes name of the certmanager, and returns the corresponding certmanager object, and an error if there is any.
func (c *certmanagers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Certmanager, err error) {
	result = &v1alpha1.Certmanager{}
	err = c.client.Get().
		Resource("certmanagers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Certmanagers that match those selectors.
func (c *certmanagers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CertmanagerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CertmanagerList{}
	err = c.client.Get().
		Resource("certmanagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested certmanagers.
func (c *certmanagers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("certmanagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a certmanager and creates it.  Returns the server's representation of the certmanager, and an error, if there is any.
func (c *certmanagers) Create(ctx context.Context, certmanager *v1alpha1.Certmanager, opts v1.CreateOptions) (result *v1alpha1.Certmanager, err error) {
	result = &v1alpha1.Certmanager{}
	err = c.client.Post().
		Resource("certmanagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(certmanager).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a certmanager and updates it. Returns the server's representation of the certmanager, and an error, if there is any.
func (c *certmanagers) Update(ctx context.Context, certmanager *v1alpha1.Certmanager, opts v1.UpdateOptions) (result *v1alpha1.Certmanager, err error) {
	result = &v1alpha1.Certmanager{}
	err = c.client.Put().
		Resource("certmanagers").
		Name(certmanager.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(certmanager).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *certmanagers) UpdateStatus(ctx context.Context, certmanager *v1alpha1.Certmanager, opts v1.UpdateOptions) (result *v1alpha1.Certmanager, err error) {
	result = &v1alpha1.Certmanager{}
	err = c.client.Put().
		Resource("certmanagers").
		Name(certmanager.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(certmanager).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the certmanager and deletes it. Returns an error if one occurs.
func (c *certmanagers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("certmanagers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *certmanagers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("certmanagers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched certmanager.
func (c *certmanagers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Certmanager, err error) {
	result = &v1alpha1.Certmanager{}
	err = c.client.Patch(pt).
		Resource("certmanagers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
