apiVersion: v1
kind: Service
metadata:
  name: cert-manager-istio-csr-metrics
  namespace: cert-manager
  labels:
    app: cert-manager-istio-csr-metrics
    app.kubernetes.io/name: cert-manager-istio-csr
    app.kubernetes.io/instance: cert-manager-istio-csr
    app.kubernetes.io/version: v0.15.0
    app.kubernetes.io/managed-by: cert-manager-operator
spec:
  type: ClusterIP
  ports:
    - port: 9402
      targetPort: 9402
      protocol: TCP
      name: metrics
  selector:
    app: cert-manager-istio-csr
