kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: cert-manager-istio-csr
    app.kubernetes.io/instance: cert-manager-istio-csr
    app.kubernetes.io/version: v0.15.0
    app.kubernetes.io/managed-by: cert-manager-operator
  name: cert-manager-istio-csr-leases
  namespace: istio-system
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
