apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cert-manager-istio-csr
    app.kubernetes.io/instance: cert-manager-istio-csr
    app.kubernetes.io/version: v0.14.2
    app.kubernetes.io/managed-by: cert-manager-operator
  name: cert-manager-istio-csr
  namespace: cert-manager
