kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: cert-manager-istio-csr
    app.kubernetes.io/instance: cert-manager-istio-csr
    app.kubernetes.io/version: v0.14.2
    app.kubernetes.io/managed-by: cert-manager-operator
  name: cert-manager-istio-csr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-istio-csr
subjects:
  - kind: ServiceAccount
    name: cert-manager-istio-csr
    namespace: cert-manager
