// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/openshift/cert-manager-operator/apis/config/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CertmanagerLister helps list Certmanagers.
// All objects returned here must be treated as read-only.
type CertmanagerLister interface {
	// List lists all Certmanagers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Certmanager, err error)
	// Get retrieves the Certmanager from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.Certmanager, error)
	CertmanagerListerExpansion
}

// certmanagerLister implements the CertmanagerLister interface.
type certmanagerLister struct {
	indexer cache.Indexer
}

// NewCertmanagerLister returns a new CertmanagerLister.
func NewCertmanagerLister(indexer cache.Indexer) CertmanagerLister {
	return &certmanagerLister{indexer: indexer}
}

// List lists all Certmanagers in the indexer.
func (s *certmanagerLister) List(selector labels.Selector) (ret []*v1alpha1.Certmanager, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Certmanager))
	})
	return ret, err
}

// Get retrieves the Certmanager from the index for a given name.
func (s *certmanagerLister) Get(name string) (*v1alpha1.Certmanager, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("certmanager"), name)
	}
	return obj.(*v1alpha1.Certmanager), nil
}
