apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-http01-proxy
  labels:
    app: cert-manager-http01-proxy
    app.kubernetes.io/name: cert-manager-http01-proxy
    app.kubernetes.io/part-of: cert-manager-operator
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
      - infrastructures
      - ingresses
    verbs:
      - get
      - list
      - watch
