apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-http01-proxy
  namespace: cert-manager-operator
  labels:
    app: cert-manager-http01-proxy
    app.kubernetes.io/name: cert-manager-http01-proxy
    app.kubernetes.io/part-of: cert-manager-operator
