apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: operator-deny-all-traffic
spec:
  podSelector:
    matchLabels:
      name: cert-manager-operator
  policyTypes:
    - Ingress
    - Egress
