---
apiVersion: v1
kind: Service
metadata:
  name: trust-manager-metrics
  namespace: cert-manager
  labels:
    app: cert-manager-trust-manager
    app.kubernetes.io/name: cert-manager-trust-manager
    app.kubernetes.io/instance: cert-manager-trust-manager
    app.kubernetes.io/version: "v0.20.3"
    app.kubernetes.io/managed-by: cert-manager-operator
    app.kubernetes.io/part-of: cert-manager-operator
spec:
  type: ClusterIP
  ports:
    - port: 9402
      targetPort: 9402
      protocol: TCP
      name: metrics
  selector:
    app: cert-manager-trust-manager
