apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: trust-manager
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager-trust-manager
    app.kubernetes.io/instance: cert-manager-trust-manager
    app.kubernetes.io/version: "v0.20.3"
    app.kubernetes.io/managed-by: cert-manager-operator
    app.kubernetes.io/part-of: cert-manager-operator
