// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/pkg/operator/applyconfigurations/operator/v1alpha1"
	typedoperatorv1alpha1 "github.com/openshift/cert-manager-operator/pkg/operator/clientset/versioned/typed/operator/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeTrustManagers implements TrustManagerInterface
type fakeTrustManagers struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.TrustManager, *v1alpha1.TrustManagerList, *operatorv1alpha1.TrustManagerApplyConfiguration]
	Fake *FakeOperatorV1alpha1
}

func newFakeTrustManagers(fake *FakeOperatorV1alpha1) typedoperatorv1alpha1.TrustManagerInterface {
	return &fakeTrustManagers{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.TrustManager, *v1alpha1.TrustManagerList, *operatorv1alpha1.TrustManagerApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("trustmanagers"),
			v1alpha1.SchemeGroupVersion.WithKind("TrustManager"),
			func() *v1alpha1.TrustManager { return &v1alpha1.TrustManager{} },
			func() *v1alpha1.TrustManagerList { return &v1alpha1.TrustManagerList{} },
			func(dst, src *v1alpha1.TrustManagerList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.TrustManagerList) []*v1alpha1.TrustManager {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.TrustManagerList, items []*v1alpha1.TrustManager) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
