// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCertmanagers implements CertmanagerInterface
type FakeCertmanagers struct {
	Fake *FakeOperatorV1alpha1
}

var certmanagersResource = schema.GroupVersionResource{Group: "operator.openshift.io", Version: "v1alpha1", Resource: "certmanagers"}

var certmanagersKind = schema.GroupVersionKind{Group: "operator.openshift.io", Version: "v1alpha1", Kind: "Certmanager"}

// Get takes name of the certmanager, and returns the corresponding certmanager object, and an error if there is any.
func (c *FakeCertmanagers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Certmanager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(certmanagersResource, name), &v1alpha1.Certmanager{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Certmanager), err
}

// List takes label and field selectors, and returns the list of Certmanagers that match those selectors.
func (c *FakeCertmanagers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CertmanagerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(certmanagersResource, certmanagersKind, opts), &v1alpha1.CertmanagerList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CertmanagerList{ListMeta: obj.(*v1alpha1.CertmanagerList).ListMeta}
	for _, item := range obj.(*v1alpha1.CertmanagerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested certmanagers.
func (c *FakeCertmanagers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(certmanagersResource, opts))
}

// Create takes the representation of a certmanager and creates it.  Returns the server's representation of the certmanager, and an error, if there is any.
func (c *FakeCertmanagers) Create(ctx context.Context, certmanager *v1alpha1.Certmanager, opts v1.CreateOptions) (result *v1alpha1.Certmanager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(certmanagersResource, certmanager), &v1alpha1.Certmanager{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Certmanager), err
}

// Update takes the representation of a certmanager and updates it. Returns the server's representation of the certmanager, and an error, if there is any.
func (c *FakeCertmanagers) Update(ctx context.Context, certmanager *v1alpha1.Certmanager, opts v1.UpdateOptions) (result *v1alpha1.Certmanager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(certmanagersResource, certmanager), &v1alpha1.Certmanager{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Certmanager), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCertmanagers) UpdateStatus(ctx context.Context, certmanager *v1alpha1.Certmanager, opts v1.UpdateOptions) (*v1alpha1.Certmanager, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(certmanagersResource, "status", certmanager), &v1alpha1.Certmanager{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Certmanager), err
}

// Delete takes name of the certmanager and deletes it. Returns an error if one occurs.
func (c *FakeCertmanagers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(certmanagersResource, name), &v1alpha1.Certmanager{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCertmanagers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(certmanagersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CertmanagerList{})
	return err
}

// Patch applies the patch and returns the patched certmanager.
func (c *FakeCertmanagers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Certmanager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(certmanagersResource, name, pt, data, subresources...), &v1alpha1.Certmanager{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Certmanager), err
}
