---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-approver-policy-tls
  namespace: "cert-manager"
  annotations:
    cert-manager.io/allow-direct-injection: "true"
  labels:
    app: cert-manager-approver-policy
    app.kubernetes.io/name: cert-manager-approver-policy
    app.kubernetes.io/instance: cert-manager-approver-policy
    app.kubernetes.io/version: "v0.27.0"
    app.kubernetes.io/managed-by: cert-manager-operator
    app.kubernetes.io/part-of: cert-manager-operator
